=== gasyoun/SanskritLexicography/data/dhp/westwork/WestergaardDhP.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT wdpsections (section )*>
<!ELEMENT section (text , (sutra | subsection | section)* )>
<!ELEMENT subsection (sutra | subsection)* >
<!ELEMENT sutra  (root | mdproot | sense | mdpsutra)* >
<!ELEMENT root (#PCDATA)* >
<!ELEMENT mdproot (#PCDATA)* >
<!ELEMENT sense (#PCDATA)* >
<!ELEMENT mdpsutra (#PCDATA)* >
<!ELEMENT text (#PCDATA)* >
<!ATTLIST section id   CDATA #IMPLIED >
<!ATTLIST section vp   CDATA #IMPLIED >
<!ATTLIST section numroots  CDATA #IMPLIED >
<!ATTLIST section nfound  CDATA #IMPLIED >
<!ATTLIST sutra msid  CDATA #IMPLIED >
<!ATTLIST sutra comment  CDATA #IMPLIED >
<!ATTLIST root wsid   CDATA #IMPLIED >
<!ATTLIST mdproot wsid   CDATA #IMPLIED >
<!ATTLIST root mdp  CDATA #IMPLIED >
<!ATTLIST root mdp1  CDATA #IMPLIED >
<!ATTLIST root nomdp   CDATA #IMPLIED >
<!ATTLIST sense mdp  CDATA #IMPLIED >

=== gasyoun/SanskritLexicography/data/dhp/westwork/wdp-mw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wdpsections SYSTEM "WestergaardDhP.dtd">
<wdpsections>
<section id="I.A.1" vp="344" numroots="1" nfound="1"><text>1. {sd parasmEBAzaH}</text>
<sutra msid="01.0001"><root wsid="1.1">BU</root><sense>sattAyAm</sense></sutra>
</section>
<section id="I.A.2" vp="344" numroots="36" nfound="36"><text>2. {sd tavargIyAntA anudattetaH}</text>
<sutra msid="01.0003"><root wsid="2.1">eDa</root><sense>vfdDO</sense></sutra>
<sutra msid="01.0004"><root wsid="2.2">spardDa</root><sense>saNGarze</sense></sutra>
<sutra msid="01.0005"><root wsid="2.3">gADf</root><sense>pratizWAlipsayorgranTe ca</sense></sutra>
<sutra msid="01.0006"><root wsid="2.4">bADf</root><sense>loqane</sense></sutra>
<sutra msid="01.0007"><root wsid="2.5">nADf</root><root wsid="2.6">nATf</root><sense mdp="yAYcopatApESvaryASIHzu">yAcYopatApESvaryASIHzu</sense></sutra>
<sutra msid="01.0008"><root wsid="2.7">daDa</root><sense>DAraRe</sense></sutra>
<sutra msid="01.0009"><root wsid="2.8">skudi</root><sense>ApravaRe</sense></sutra>
<sutra msid="01.0010"><root wsid="2.9">Svidi</root><sense>SvEtye</sense></sutra>
<sutra msid="01.0011"><root wsid="2.10">vadi</root><sense>aBivAdanastutyoH</sense></sutra>
<sutra msid="01.0012"><root wsid="2.11">Badi</root><sense>kalyARe suKe ca</sense></sutra>
<sutra msid="01.0013"><root wsid="2.12">madi</root><sense>stutimodamadasvapnakAntigatizu</sense></sutra>
<sutra msid="01.0014"><root wsid="2.13">spadi</root><sense>kiYciccalane</sense></sutra>
<sutra msid="01.0015"><root wsid="2.14">klidi</root><sense>paridevane</sense></sutra>
<sutra msid="01.0016"><root wsid="2.15">muda</root><sense>harze</sense></sutra>
<sutra msid="01.0017"><root wsid="2.16">dada</root><sense>dAne</sense></sutra>
<sutra msid="01.0018"><root wsid="2.17">zvada</root><root wsid="2.18">svarda</root><sense>AsvAdane</sense></sutra>
<sutra msid="01.0019"><root wsid="2.19">urda</root><sense>mAne krIqAyAM ca</sense></sutra>
<sutra msid="01.0020"><root wsid="2.20">kurda</root><root wsid="2.21">Kurda</root><root wsid="2.22">gurda</root><root wsid="2.23">guda</root><sense>krIqAyAmeva</sense></sutra>
<sutra msid="01.0021"><root wsid="2.24">zUda</root><sense mdp="kzaraRe">kzaRane</sense></sutra>
<sutra msid="01.0022"><root wsid="2.25">hrAda</root><sense>avyakte Sabde</sense></sutra>
<sutra msid="01.0023"><root wsid="2.26">hlAdI</root><sense>suKe ca</sense></sutra>
<sutra msid="01.0024"><root wsid="2.27">svAda</root><sense>AsvAdane</sense></sutra>
<sutra msid="01.0025"><root wsid="2.28">parda</root><sense mdp="kutsite Sabde">kutsitaSabde</sense></sutra>
<sutra msid="01.0026"><root wsid="2.29">yatI</root><sense>prayatne</sense></sutra>
<sutra msid="01.0027"><root wsid="2.30">yutf</root><root wsid="2.31">jutf</root><sense>BAsane</sense></sutra>
<sutra msid="01.0028"><root wsid="2.32">viTf</root><root wsid="2.33">veTf</root><sense>yAcane</sense></sutra>
<sutra msid="01.0029"><root wsid="2.34">SraTi</root><sense>SETilye</sense></sutra>
<sutra msid="01.0030"><root wsid="2.35">graTi</root><sense>kOwilye</sense></sutra>
<sutra msid="01.0031"><root wsid="2.36">katTa</root><sense>SlAGAyAm</sense></sutra>
</section>
<section id="I.A.3" vp="344-345" numroots="37" nfound="40"><text>3. {sd tavargIyAntA udattetaH}</text>
<sutra msid="01.0033"><root wsid="3.1">ata</root><sense>sAtatyagamane</sense></sutra>
<sutra msid="01.0034"><root wsid="3.2">citI</root><sense>saMjYAne</sense></sutra>
<sutra msid="01.0035"><root wsid="3.3">cyutir</root><sense>Asecane</sense></sutra>
<sutra msid="01.0036"><root wsid="3.4">Scyutir</root><sense>kzaraRe</sense></sutra>
<sutra msid="01.0037"><root wsid="3.5">manTa</root><sense>viloqane</sense></sutra>
<sutra msid="01.0038"><root wsid="3.6">kuTi</root><root wsid="3.7">puTi</root><root wsid="3.8">luTi</root><root wsid="3.9">maTi</root><mdproot wsid="3.X10">mAnTa</mdproot><sense mdp="hiMsAsaNkleSanayoH">hiMsAsaNkleSayoH</sense></sutra>
<sutra msid="01.0039"><root wsid="3.10">ziDa</root><sense>gatyAm</sense></sutra>
<sutra msid="01.0040"><root wsid="3.11">ziDU</root><sense>SAstre mANgalye ca</sense></sutra>
<sutra msid="01.0041"><root wsid="3.12">KAdf</root><sense>BakzaRe</sense></sutra>
<sutra msid="01.0042"><root wsid="3.13">Kada</root><sense>sTErye hiMsAyAM ca</sense></sutra>
<sutra msid="01.0043"><root wsid="3.14">bada</root><sense>sTErye</sense></sutra>
<sutra msid="01.0044"><root wsid="3.15">gada</root><sense>vyaktAyAM vAci</sense></sutra>
<sutra msid="01.0045"><root wsid="3.16">rada</root><sense>vileKane</sense></sutra>
<sutra msid="01.0046"><root wsid="3.17">Rada</root><sense>avyakte Sabde</sense></sutra>
<sutra msid="01.0047"><root wsid="3.18">arda</root><sense>gatO yAcane ca</sense></sutra>
<sutra msid="01.0048"><root wsid="3.19">narda</root><root wsid="3.20">garda</root><sense>Sabde</sense></sutra>
<sutra msid="01.0049"><root wsid="3.21">tarda</root><sense>hiMsAyAm</sense></sutra>
<sutra msid="01.0050"><root wsid="3.22">karda</root><sense>kutsite Sabde</sense></sutra>
<sutra msid="01.0051"><root wsid="3.23">Karda</root><sense>dandaSUke</sense></sutra>
<sutra msid="01.0052"><root wsid="3.24">ati</root><root wsid="3.25">adi</root><sense>banDane</sense></sutra>
<sutra msid="01.0053"><root wsid="3.26">idi</root><sense>paramESvarye</sense></sutra>
<sutra msid="01.0054"><root wsid="3.27">bidi</root><sense>avayave</sense></sutra>
<sutra msid="01.0055"><mdproot wsid="3.X28">gaqi</mdproot><sense>vadanEkadeSe</sense></sutra>
<sutra msid="01.0056"><root wsid="3.28">Ridi</root><sense>kutsAyAm</sense></sutra>
<sutra msid="29"><sense>--></sense></sutra>
<sutra msid="01.0057"><root wsid="3.30">wunadi</root><sense>samfdDO</sense></sutra>
<sutra msid="01.0058"><root wsid="3.31">cadi</root><sense>AhlAdane dIptO ca</sense></sutra>
<sutra msid="01.0059"><root wsid="3.32">tradi</root><sense>cezwAyAm</sense></sutra>
<sutra msid="01.0060"><root wsid="3.33">kadi</root><root wsid="3.34">kradi</root><root wsid="3.35">kladi</root><sense>AhvAne rodane ca</sense></sutra>
<sutra msid="01.0061"><root wsid="3.36">klidi</root><sense>paridevane</sense></sutra>
<sutra msid="01.0062"><root wsid="3.37">SunDa</root><sense>SudDO</sense></sutra>
</section>
<section id="I.A.4" vp="345-346" numroots="41" nfound="41"><text>4. {sd kavargIyAntA anudattetaH}</text>
<sutra msid="01.0064"><root wsid="4.1">SIkf</root><sense>secane</sense></sutra>
<sutra msid="01.0065"><root wsid="4.2">lokf</root><sense>darSane</sense></sutra>
<sutra msid="01.0066"><root wsid="4.3">Slokf</root><sense>saNGAte</sense></sutra>
<sutra msid="01.0067"><root wsid="4.4">drekf</root><root wsid="4.5">Drekf</root><sense mdp="SabdotsAhayoH">SabdotsahaM karoti</sense></sutra>
<sutra msid="01.0068"><root wsid="4.6">rekf</root><sense>SaNkAyAm</sense></sutra>
<sutra msid="01.0069"><root wsid="4.7">sekf</root><root wsid="4.8">srekf</root><root wsid="4.9">sraki</root><root wsid="4.10">Sraki</root><root wsid="4.11">Slaki</root><sense>gatyarTAH</sense></sutra>
<sutra msid="01.0070"><root wsid="4.12">Saki</root><sense>SaNkAyAm</sense></sutra>
<sutra msid="01.0071"><root wsid="4.13">aki</root><sense>lakzaRe</sense></sutra>
<sutra msid="01.0072"><root wsid="4.14">vaki</root><sense>kOwilye</sense></sutra>
<sutra msid="01.0073"><root wsid="4.15">maki</root><sense>maRqane</sense></sutra>
<sutra msid="01.0074"><root wsid="4.16">kaka</root><sense>lOlye</sense></sutra>
<sutra msid="01.0075"><root wsid="4.17">kuka</root><root wsid="4.18">vfka</root><sense>AdAne</sense></sutra>
<sutra msid="01.0076"><root wsid="4.19">caka</root><sense mdp="tfptO pratiGAte ca">tfptO</sense></sutra>
<sutra msid="01.0077"><root wsid="4.20">kaki</root><root wsid="4.21">vaki</root><root wsid="4.22">Svaki</root><root wsid="4.23">traki</root><root wsid="4.24">QOkf</root><root wsid="4.25">trOkf</root><root wsid="4.26">zvazka</root><root wsid="4.27">vaska</root><root wsid="4.28">maska</root><root wsid="4.29">wikf</root><root wsid="4.30">wIkf</root><root wsid="4.31" nomdp="yes">tikf</root><root wsid="4.32" nomdp="yes">tIkf</root><root wsid="4.33">raGi </root><root wsid="4.34">laGi</root><sense>gatyarTAH</sense></sutra>
<sutra msid="01.0078"><root wsid="4.35">aGi</root><root wsid="4.36">vaGi</root><root wsid="4.37">maGi</root><sense>gatyAkzepe</sense></sutra>
<sutra msid="01.0079"><mdproot wsid="4.X38">maGi {wdp pA}</mdproot><sense>kEtave ca</sense></sutra>
<sutra msid="01.0080"><root wsid="4.38">rAGf</root><root wsid="4.39">lAGf</root><root wsid="4.40">drAGf</root><sense>sAmarTye</sense></sutra>
<sutra msid="01.0081"><root wsid="4.40">drAGf {wdp number repeated}</root><sense>AyAme ca</sense></sutra>
<sutra msid="01.0082"><root wsid="4.41">SlAGf</root><sense>katTane</sense></sutra>
</section>
<section id="I.A.5" vp="346" numroots="58" nfound="47"><text>5. {sd kavargIyAntA udattetaH}</text>
<sutra msid="01.0084"><root wsid="5.1">Pakka</root><sense mdp="nIcErgatO">nicErgatO</sense></sutra>
<sutra msid="01.0085"><root wsid="5.2">taka</root><sense>hasane</sense></sutra>
<sutra msid="01.0086"><root wsid="5.3">taki</root><sense>kfcCrajIvane</sense></sutra>
<sutra msid="01.0087"><root wsid="5.4">bukka</root><sense>BazaRe</sense></sutra>
<sutra msid="01.xxxx"><root wsid="5.5" nomdp="yes">Suka</root><sense>gatO</sense></sutra>
<sutra msid="01.0088"><root wsid="5.6">kaKa</root><sense>hasane</sense></sutra>
<sutra msid="01.0089"><root wsid="5.7">oKf</root><root wsid="5.8">rAKf</root><root wsid="5.9">lAKf</root><root wsid="5.10">drAKf</root><root wsid="5.11">DrAKf</root><sense>SozaRAlamarTayoH</sense></sutra>
<sutra msid="01.0090"><root wsid="5.12">SAKf</root><root wsid="5.13">SlAKf</root><sense>vyAptO</sense></sutra>
